name: Build TNOB Calendar

on:
  workflow_dispatch:
  schedule:
    - cron: "0 2 1 * *" # каждый 1-й день месяца в 02:00 UTC

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Run generator
        run: node generate.js

      - name: Commit calendar
        run: |
          git config --global user.name "calendar-bot"
          git config --global user.email "calendar-bot@users.noreply.github.com"
          git pull
          git add calendar.ics
          git commit -m "update calendar" || echo "no changes"
          git push origin main
